Source/QuanLyNhaHang/Controllers/KhachHangController.cs
using System;
using ApplicationCore.DTOs.SaveDTOs;
using ApplicationCore.Interfaces.IServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuanLyNhaHang.Services.Interfaces;
using QuanLyNhaHang.ViewModels;

namespace QuanLyNhaHang.Controllers
{
    public class KhachHangController : Controller
    {
        private readonly IKhachHangServices _services;
        private readonly IKhachHangIndexVMServices _servicesIndexVM;
        public KhachHangController(IKhachHangServices services, IKhachHangIndexVMServices servicesIndexVM)
        {
            this._services = services;
            this._servicesIndexVM = servicesIndexVM;
        }

        public bool KiemTraDangNhap()
        {
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("TenDangNhapCurrentUser")))
            {
                return false;
            }
            else
            {
                ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                return true;
            }
        }
        public IActionResult Index(string Ten, string SDT, string DiaChi, string currentSort, string currentFilterTen, string currentFilterSDT, string currentFilterDiaChi, int pageIndex = 1)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (!String.IsNullOrEmpty(Ten) || !String.IsNullOrEmpty(SDT) || !String.IsNullOrEmpty(DiaChi))
                pageIndex = 1;
            if (String.IsNullOrEmpty(Ten))
                Ten = currentFilterTen;
            if (String.IsNullOrEmpty(SDT))
                SDT = currentFilterSDT;
            if (String.IsNullOrEmpty(DiaChi))
                DiaChi = currentFilterDiaChi;
            @ViewBag.CurrentFilterTen = Ten;
            @ViewBag.CurrentFilterSDT = SDT;
            @ViewBag.CurrentFilterDiaChi = DiaChi;
            if (String.IsNullOrEmpty(currentSort))
                currentSort = "Ten_DESC";
            @ViewBag.CurrentSortTen = currentSort.Equals("Ten_DESC") ? "Ten_ASC" : "Ten_DESC";
            @ViewBag.CurrentSortSDT = currentSort.Equals("SDT_DESC") ? "SDT_ASC" : "SDT_DESC";
            @ViewBag.CurrentSortDiaChi = currentSort.Equals("DiaChi_DESC") ? "DiaChi_ASC" : "DiaChi_DESC";

            @ViewBag.CurrentSort = currentSort;
            KhachHangVM khachHangVM = _servicesIndexVM.GetKhachHangVM(currentSort, Ten, SDT, DiaChi, pageIndex);
            return View(khachHangVM);
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            return View();
        }

        [HttpPost]
        public IActionResult Create(SaveKhachHangDTO SaveKhachHangDTO)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (!ModelState.IsValid)
            {
                return View(SaveKhachHangDTO);
            }
            _services.Create(SaveKhachHangDTO);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            SaveKhachHangDTO saveKhachHangDTO = _services.GetSaveKhachHangDTO(id.Value);
            if (saveKhachHangDTO == null)
                return RedirectToAction("Index");
            return View(saveKhachHangDTO);
        }
        [HttpPost]
        public IActionResult Edit(SaveKhachHangDTO saveKhachHangDTO)
        {
            if (!ModelState.IsValid)
                return View(saveKhachHangDTO);
            _services.Edit(saveKhachHangDTO);
            return RedirectToAction("Index");
        }

        public IActionResult Detail(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            return View(_services.GetKhachHang(id.Value));
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            return View(_services.GetSaveKhachHangDTO(id.Value));
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult Deleted(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            int i = _services.Delete(id.Value);
            if (i.Equals(-1))
            {
                ViewBag.MessageDeleteError = "Danh sách phiếu đặt bàn của khách hàng bị null";
                return View(_services.GetSaveKhachHangDTO(id.Value));
            }
            else if (i.Equals(0))
            {
                ViewBag.MessageDeleteError = "Khách hàng này đã có phiếu đặt bàn, không thể xóa";
                return View(_services.GetSaveKhachHangDTO(id.Value));
            }
            return RedirectToAction("Index");
        }
    }
}

Source/QuanLyNhaHang/Controllers/PhieuDatBanController.cs
using System;
using System.Data;
using System.Globalization;
using System.Net;
using ApplicationCore.DTOs;
using ApplicationCore.DTOs.SaveDTOs;
using ApplicationCore.Entities;
using ApplicationCore.Interfaces.IServices;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuanLyNhaHang.Services.Interfaces;
using QuanLyNhaHang.ViewModels;

namespace QuanLyNhaHang.Controllers
{
    public class PhieuDatBanController : Controller
    {
        private readonly IPhieuDatBanServices _services;
        private readonly IPhieuDatBanIndexVMServices _servicesIndexVM;
        private readonly IMapper _mapper;
        public PhieuDatBanController(IPhieuDatBanServices services, IPhieuDatBanIndexVMServices servicesIndexVM, IMapper mapper)
        {
            this._services = services;
            this._servicesIndexVM = servicesIndexVM;
            this._mapper = mapper;
        }

        public bool KiemTraDangNhap()
        {
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("TenDangNhapCurrentUser")))
            {
                return false;
            }
            else
            {
                ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                return true;
            }
        }

        public IActionResult Index(int idBanAn, string trangThai, string currentSort, string currentFilterIdBanAn, string currentFilterTrangThai, int pageIndex = 1)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (String.IsNullOrEmpty(idBanAn.ToString()))
                idBanAn = 0;
            if (!idBanAn.Equals(0))
            {
                pageIndex = 1;
            }
            else if (!String.IsNullOrEmpty(currentFilterIdBanAn))
            {
                idBanAn = Convert.ToInt32(currentFilterIdBanAn.ToString());
            }

            if (!String.IsNullOrEmpty(trangThai))
            {
                pageIndex = 1;
            }
            else
            {
                trangThai = currentFilterTrangThai;
            }
            ViewBag.CurrentFilterTrangThai = trangThai;
            ViewBag.CurrentFilterIdBanAn = idBanAn;

            if (String.IsNullOrEmpty(currentSort))
                currentSort = "BanAn_DESC";
            ViewBag.CurrentSortIdBanAn = currentSort.Equals("BanAn_DESC") ? "BanAn_ASC" : "BanAn_DESC";
            ViewBag.CurrentSortTrangThai = currentSort.Equals("TrangThai_DESC") ? "TrangThai_ASC" : "TrangThai_DESC";
            ViewBag.CurrentSortThoiGianDat = currentSort.Equals("ThoiGianDat_DESC") ? "ThoiGianDat_ASC" : "ThoiGianDat_DESC";
            ViewBag.CurrentSortTenKhachHang = currentSort.Equals("TenKhachHang_DESC") ? "TenKhachHang_ASC" : "TenKhachHang_DESC";

            ViewBag.CurrentSort = currentSort;
            PhieuDatBanVM vm = _servicesIndexVM.GetPhieuDatBanVM(currentSort, idBanAn, trangThai, pageIndex);
            return View(vm);
        }

        public IActionResult Edit(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (id == null)
                return RedirectToAction("Index");
            PhieuDatBanDTO pDTO = _services.GetById(id.Value);
            if (pDTO == null)
                return RedirectToAction("Index");

            SavePhieuDatBanDTO savePhieuDatBanDTO = _mapper.Map<PhieuDatBanDTO, SavePhieuDatBanDTO>(pDTO);
            KhachHang kh = _services.GetKhachHang(savePhieuDatBanDTO.IdKhachHang);
            ViewBag.TenKhachHang = kh.Ten;

            NguoiDung nguoiDung = _services.GetNguoiDung(savePhieuDatBanDTO.IdUser);
            ViewBag.TenUser = nguoiDung.Ten;
            
            PhieuDatBanVM vm = new PhieuDatBanVM
            {
                PhieuDatBan = savePhieuDatBanDTO,
                BanAns = _services.GetListBanAn()
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Edit(PhieuDatBanVM vm)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (_services.Update(vm.PhieuDatBan) == false)
            {
                ViewBag.MessagePhieuDatBan = "Thời gian đặt bị trùng";
                KhachHang kh = _services.GetKhachHang(vm.PhieuDatBan.IdKhachHang);
                ViewBag.TenKhachHang = kh.Ten;
                NguoiDung nguoiDung = _services.GetNguoiDung(vm.PhieuDatBan.IdUser);
                ViewBag.TenUser = nguoiDung.Ten;
                vm = new PhieuDatBanVM
                {
                    PhieuDatBan = vm.PhieuDatBan,
                    BanAns = _services.GetListBanAn()
                };
                return View(vm);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Create(int? IdKhachHang)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            PhieuDatBanVM vm = null;
            System.DateTime day = DateTime.Now;
            ViewBag.CurrentTime = DateTime.Now;

            if (IdKhachHang == null)
            {

                vm = new PhieuDatBanVM
                {
                    PhieuDatBan = new SavePhieuDatBanDTO
                    {
                        ThoiGianDat = Convert.ToDateTime(day),
                    },
                    BanAns = _services.GetListBanAn(),
                    KhachHangs = _services.GetListKH()
                };

            }
            else
            {
                vm = new PhieuDatBanVM
                {
                    PhieuDatBan = new SavePhieuDatBanDTO
                    {
                        IdKhachHang = IdKhachHang.Value,
                        ThoiGianDat = Convert.ToDateTime(day),
                    },
                    BanAns = _services.GetListBanAn(),
                    KhachHangs = _services.GetListKH()
                };
            }

            return View(vm);
        }

        [HttpPost]
        public IActionResult Create(PhieuDatBanVM vm)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            SavePhieuDatBanDTO p = new SavePhieuDatBanDTO
            {
                IdBanAn = vm.PhieuDatBan.IdBanAn,
                IdKhachHang = vm.PhieuDatBan.IdKhachHang,
                IdUser = vm.PhieuDatBan.IdUser,
                ThoiGianDat = vm.PhieuDatBan.ThoiGianDat,
                GhiChu = vm.PhieuDatBan.GhiChu
            };
            int i = _services.Add(p);

            if (i == -2)
            {
                ViewBag.MessagePhieuDatBan = "Khách hàng này không tồn tại";
                System.DateTime day = DateTime.Now;
                vm = new PhieuDatBanVM
                {
                    PhieuDatBan = new SavePhieuDatBanDTO
                    {
                        IdBanAn = vm.PhieuDatBan.IdBanAn,
                        IdKhachHang = p.IdKhachHang,
                        IdUser = vm.PhieuDatBan.IdUser,
                        ThoiGianDat = Convert.ToDateTime(day),
                        GhiChu = vm.PhieuDatBan.GhiChu,
                    },
                    BanAns = _services.GetListBanAn(),
                    KhachHangs = _services.GetListKH()
                };
                return View(vm);
            }
            if (i == 0)
            {
                ViewBag.MessagePhieuDatBan = "Bàn này đã có người đặt";
                System.DateTime day = DateTime.Now;
                vm = new PhieuDatBanVM
                {
                    PhieuDatBan = new SavePhieuDatBanDTO
                    {
                        IdBanAn = vm.PhieuDatBan.IdBanAn,
                        IdKhachHang = p.IdKhachHang,
                        IdUser = vm.PhieuDatBan.IdUser,
                        ThoiGianDat = Convert.ToDateTime(day),
                        GhiChu = vm.PhieuDatBan.GhiChu,
                    },
                    BanAns = _services.GetListBanAn(),
                    KhachHangs = _services.GetListKH()
                };
                return View(vm);
            }
            else if (i == -1)
            {
                ViewBag.MessagePhieuDatBan = "Bàn này đang được phục vụ";
                System.DateTime day = DateTime.Now;
                vm = new PhieuDatBanVM
                {
                    PhieuDatBan = new SavePhieuDatBanDTO
                    {
                        IdBanAn = vm.PhieuDatBan.IdBanAn,
                        IdKhachHang = p.IdKhachHang,
                        IdUser = vm.PhieuDatBan.IdUser,
                        ThoiGianDat = Convert.ToDateTime(day),
                        GhiChu = vm.PhieuDatBan.GhiChu,
                    },
                    BanAns = _services.GetListBanAn(),
                    KhachHangs = _services.GetListKH()
                };
                return View(vm);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? Id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (Id == null)
                return RedirectToAction("Index");
            PhieuDatBanDTO pDTO = _services.GetById(Id.Value);
            if (pDTO == null)
                return RedirectToAction("Index");
            SavePhieuDatBanDTO savePhieuDatBanDTO = _mapper.Map<PhieuDatBanDTO, SavePhieuDatBanDTO>(pDTO);
            KhachHang kh = _services.GetKhachHang(savePhieuDatBanDTO.IdKhachHang);
            NguoiDung nguoiDung = _services.GetNguoiDung(savePhieuDatBanDTO.IdUser);
            ViewBag.TenUser = nguoiDung.Ten;
            ViewBag.TenKhachHang = kh.Ten;
            return View(savePhieuDatBanDTO);
        }

        [HttpPost]
        [ActionName("Delete")]

Source/QuanLyNhaHang/Views/KhachHang/Create.cshtml
@model ApplicationCore.DTOs.SaveDTOs.SaveKhachHangDTO

@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SDT" class="control-label"></label>
                <input asp-for="SDT" class="form-control" />
                <span asp-validation-for="SDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Source/QuanLyNhaHang/Views/KhachHang/Delete.cshtml
@model ApplicationCore.DTOs.SaveDTOs.SaveKhachHangDTO

@{
    ViewData["Title"] = "Quản lý khách hàng";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SDT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SDT)
        </dd>
    </dl>
    <div><i style="color:red">@ViewBag.MessageDeleteError </i></div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Source/QuanLyNhaHang/Views/KhachHang/Edit.cshtml
@model ApplicationCore.DTOs.SaveDTOs.SaveKhachHangDTO

@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SDT" class="control-label"></label>
                <input asp-for="SDT" class="form-control" />
                <span asp-validation-for="SDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Source/QuanLyNhaHang/Views/KhachHang/Index.cshtml
@model QuanLyNhaHang.ViewModels.KhachHangVM

@{
    ViewData["Title"] = "Quản lý khách hàng";
}

<div class="row">
             <div class="col-md-12">
                <p><a asp-action="Create">+ Create New</a></p>
                <hr/>
            </div>
            <form asp-action="Index" asp-controller="KhachHang" method="get">
                <div class="input-group col-sm-3">
                    <p style="margin:7px 15px 5px 0px">Tên khách hàng</p>
                    <input type="text" class="form-control" name="Ten" value="@ViewBag.CurrentFilterTen">
                 </div>

                <div class="input-group col-sm-1" ></div>

                <div class="input-group col-sm-3">
                    <p style="margin:7px 15px 5px 0px">SDT</p>
                    <input type="text" class="form-control" name="SDT" value="@ViewBag.CurrentFilterSDT">
                </div>
                <div class="input-group col-sm-3">
                    <p style="margin:7px 15px 5px 0px">Địa chỉ</p>
                    <input type="text" class="form-control" name="DiaChi" value="@ViewBag.CurrentFilterDiaChi">
                 </div>
                 
                <div class="input-group col-sm-1" ></div>

                <div class="input-group col-sm-1" >
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">Tìm</button>
                    </span>
                </div>
            
            </form>
</div>

		<div class="row">
            <div class="col-lg-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Danh sách khách hàng</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="table-responsive">
                            <table class="table table-striped jambo_table no-margin">
                                <thead>
                                    <tr>
                                        <th>
                                            <a  asp-action="Index" asp-controller="KhachHang"  style="color:white"
                                                asp-route-currentSort="@ViewBag.CurrentSortTen" 
                                                asp-route-currentFilterTen="@ViewBag.CurrentFilterTen"
                                                asp-route-currentFilterSDT="@ViewBag.CurrentFilterSDT"
                                                asp-route-currentFilterDiaChi="@ViewBag.CurrentFilterDiaChi"
                                                asp-route-pageIndex="@Model.KhachHangs.PageIndex">Tên</a>
                                            
                                        </th>
                                        <th>
                                            <a  asp-action="Index" asp-controller="KhachHang"  style="color:white"
                                                asp-route-currentSort="@ViewBag.CurrentSortSDT" 
                                                asp-route-currentFilterTen="@ViewBag.CurrentFilterTen"
                                                asp-route-currentFilterSDT="@ViewBag.CurrentFilterSDT"
                                                asp-route-currentFilterDiaChi="@ViewBag.CurrentFilterDiaChi"
                                                asp-route-pageIndex="@Model.KhachHangs.PageIndex">SDT</a>
                                        </th>
                                        <th>
                                            <a  asp-action="Index" asp-controller="KhachHang"  style="color:white"
                                                asp-route-currentSort="@ViewBag.CurrentSortDiaChi" 
                                                asp-route-currentFilterTen="@ViewBag.CurrentFilterTen"
                                                asp-route-currentFilterSDT="@ViewBag.CurrentFilterSDT"
                                                asp-route-currentFilterDiaChi="@ViewBag.CurrentFilterDiaChi"
                                                asp-route-pageIndex="@Model.KhachHangs.PageIndex">Địa chỉ</a>
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                        
                                    @foreach (var item in Model.KhachHangs) {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Ten)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SDT)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DiaChi)
                                        </td>
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                                            <a asp-action="Create" asp-controller="PhieuDatBan" asp-route-IdKhachHang="@item.Id">Lập phiếu đặt bàn</a> 
                                        </td>
                                    </tr>
                                    
                                    }
                                </tbody>
                            </table>
                        </div>

                        <div class="col-md-12">
                            @{
                                var disNext= !Model.KhachHangs.HasNext ? " visibility: hidden" : "";   
                                var disPre= !Model.KhachHangs.HasPrevious ? " visibility: hidden" : "";   
                            }

                            <span style="float:right"> 
                                <ul class="pagination">
                                    <li class="page-item">
                                        <a asp-action="Index"  class="page-link" style="@disPre"
                                        asp-route-pageIndex="@( Model.KhachHangs.PageIndex - 1 )"
                                        asp-route-currentSort="@ViewBag.CurrentSort" 
                                        asp-route-currentFilterTen="@ViewBag.CurrentFilterTen"
                                        asp-route-currentFilterSDT="@ViewBag.CurrentFilterSDT"
                                        asp-route-currentFilterDiaChi="@ViewBag.CurrentFilterDiaChi"> Previous </a>
                                    </li>
                                    
                                @{
                                
                                    for(int i=1; i <= Model.KhachHangs.TotalPages; i++)
                                    {
                                        //Nếu số tổng số trang >=8 thì sẽ hiện ... và sẽ hiện trang : i-2 , i-1 , i , i+1 ,i+2
                                        if(Model.KhachHangs.TotalPages>=8 && @i>=Model.KhachHangs.PageIndex-2 && @i<=Model.KhachHangs.PageIndex+2)
                                        {
                                            if(@i==Model.KhachHangs.PageIndex-2 && @i>1)
                                            {
                                                <li class="page-item"><a class="page-link">...</a></li>
                                            }
                                            if(@i==Model.KhachHangs.PageIndex)
                                            {
                                                <li class="page-item">
                                                    <a class="page-link" style="background-color:lightblue"> @i </a>
                                                </li>   
                                            }
                                            else 
                                            {
                                                <li class="page-item">
                                                    <a class="page-link"
                                                    asp-action="Index"
                                                    asp-route-pageIndex="@i"
                                                    asp-route-currentSort="@ViewBag.CurrentSort" 
                                                    asp-route-currentFilterTen="@ViewBag.CurrentFilterTen"
                                                    asp-route-currentFilterSDT="@ViewBag.CurrentFilterSDT"
                                                    asp-route-currentFilterDiaChi="@ViewBag.CurrentFilterDiaChi"> @i </a>
                                                </li>
                                            }
                                            if(@i==Model.KhachHangs.PageIndex+2 && @i<Model.KhachHangs.TotalPages)
                                            {
                                                <li class="page-item"><a class="page-link">...</a></li>
                                            }
                                        }
                                        else if( Model.KhachHangs.TotalPages < 8 ) //Nếu số tổng số trang <8 thì sẽ hiện hết các trang
                                        {
                                            if(@i==Model.KhachHangs.PageIndex)
                                            {
                                                <li class="page-item">
                                                    <a class="page-link" style="background-color:lightblue"> @i </a>
                                                </li>   
                                            }
                                            else
                                            {
                                                <li class="page-item">
                                                    <a class="page-link"
                                                    asp-action="Index"
                                                    asp-route-pageIndex="@i"
                                                    asp-route-currentSort="@ViewBag.CurrentSort"
                                                    asp-route-currentFilterTen="@ViewBag.CurrentFilterTen"
                                                    asp-route-currentFilterSDT="@ViewBag.CurrentFilterSDT"
                                                    asp-route-currentFilterDiaChi="@ViewBag.CurrentFilterDiaChi"> @i </a>
                                                </li>
                                            }
                                        }
                                    
                                    
                                    }
                                
                                }

                                    <li class="page-item">
                                        <a asp-action="Index"  class="page-link" style="@disNext"
                                            asp-route-pageIndex="@( Model.KhachHangs.PageIndex + 1 )"
                                            asp-route-currentSort="@ViewBag.CurrentSort"
                                            asp-route-currentFilterTen="@ViewBag.CurrentFilterTen"
                                            asp-route-currentFilterSDT="@ViewBag.CurrentFilterSDT"
                                            asp-route-currentFilterDiaChi="@ViewBag.CurrentFilterDiaChi"> Next </a>
                                    </li>
                                </ul>
                            </span>
                        </div>

                    </div>
                </div>
            </div>
        </div>
            