Source/QuanLyNhaHang/Controllers/HoaDonController.cs
using System;
using System.Reflection.Metadata;
using ApplicationCore.DTOs;
using ApplicationCore.DTOs.SaveDTOs;
using ApplicationCore.Interfaces.IServices;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuanLyNhaHang.Services.Interfaces;

namespace QuanLyNhaHang.Controllers
{
    public class HoaDonController : Controller
    {
        private readonly IHoaDonServices _services;
        private readonly IHoaDonIndexVMServices _servicesIndexVM;
        private readonly IMapper _mapper;
        public HoaDonController(IHoaDonServices services, IHoaDonIndexVMServices servicesIndexVM, IMapper mapper)
        {
            this._services = services;
            this._servicesIndexVM = servicesIndexVM;
            this._mapper = mapper;
        }
        public bool KiemTraDangNhap()
        {
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("TenDangNhapCurrentUser")))
            {
                return false;
            }
            else
            {
                ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                return true;
            }
        }
        public IActionResult Index(int idBanAn, string trangThai, string currentSort, string currentFilterIdBanAn, string currentFilterTrangThai, int pageIndex = 1)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (String.IsNullOrEmpty(idBanAn.ToString()))
                idBanAn = 0;
            if (!idBanAn.Equals(0))
            {
                pageIndex = 1;
            }
            else if (!String.IsNullOrEmpty(currentFilterIdBanAn))
            {
                idBanAn = Convert.ToInt32(currentFilterIdBanAn.ToString());
            }
            
            if (!String.IsNullOrEmpty(trangThai))
            {
                pageIndex = 1;
            }
            else
            {
                trangThai = currentFilterTrangThai;
            }
            ViewBag.CurrentFilterTrangThai = trangThai;
            ViewBag.CurrentFilterIdBanAn = idBanAn;
           
            if (String.IsNullOrEmpty(currentSort))
                currentSort = "BanAn_DESC";

            ViewBag.CurrentSortIdBanAn = currentSort.Equals("BanAn_DESC") ? "BanAn_ASC" : "BanAn_DESC";
            ViewBag.CurrentSortTrangThai = currentSort.Equals("TrangThai_DESC") ? "TrangThai_ASC" : "TrangThai_DESC";
            ViewBag.CurrentSortThoiGianLap = currentSort.Equals("ThoiGianLap_DESC") ? "ThoiGianLap_ASC" : "ThoiGianLap_DESC";
            ViewBag.CurrentSortThoiGianThanhToan = currentSort.Equals("ThoiGianThanhToan_DESC") ? "ThoiGianThanhToan_ASC" : "ThoiGianThanhToan_DESC";
            ViewBag.CurrentSortTenNhanVien = currentSort.Equals("TenNhanVien_DESC") ? "TenNhanVien_ASC" : "TenNhanVien_DESC";
            ViewBag.CurrentSortThanhTien = currentSort.Equals("ThanhTien_DESC") ? "ThanhTien_ASC" : "ThanhTien_DESC";
            ViewBag.CurrentSortIdHoaDon = currentSort.Equals("IdHoaDon_DESC") ? "IdHoaDon_ASC" : "IdHoaDon_DESC";

            ViewBag.CurrentSort = currentSort;
            return View(_servicesIndexVM.GetHoaDonVM(currentSort, idBanAn, trangThai, pageIndex));
        }
        public IActionResult Delete(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (id == null)
                return RedirectToAction("Index");
            HoaDonDTO hoaDonDTO = _services.FindHD(id.Value);
            if (hoaDonDTO == null)
                return RedirectToAction("Index");
            ViewBag.UserName = _services.GetNameUser(hoaDonDTO.IdUser);
            SaveHoaDonDTO saveHoaDonDTO = _mapper.Map<HoaDonDTO, SaveHoaDonDTO>(hoaDonDTO);
            return View(saveHoaDonDTO);
        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult Deleted(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (id == null)
                return RedirectToAction("Index");

            int i = _services.Delete(id.Value);
            if (i == 0)
            {
                ViewBag.Error = "Hóa đơn này đang tính cho bàn ăn đang được phục vụ ,không thể xóa ";
                HoaDonDTO hoaDonDTO = _services.FindHD(id.Value);
                SaveHoaDonDTO saveHoaDonDTO = _mapper.Map<HoaDonDTO, SaveHoaDonDTO>(hoaDonDTO);
                ViewBag.UserName = _services.GetNameUser(hoaDonDTO.IdUser);
                return View(saveHoaDonDTO);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Details(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (id == null)
                return RedirectToAction("Index");
            HoaDonDTO hoaDonDTO = _services.FindHD(id.Value);
            if (hoaDonDTO == null)
                return RedirectToAction("Index");
            ViewBag.UserName = _services.GetNameUser(hoaDonDTO.IdUser);
            return View(_servicesIndexVM.Details(id.Value));
        }
        public IActionResult Edit(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (id == null)
                return RedirectToAction("Index");
            ViewData["ListBanAn"] = _services.GetListBanAn();
            SaveHoaDonDTO saveHoaDonDTO = _mapper.Map<HoaDonDTO, SaveHoaDonDTO>(_services.FindHD(id.Value));
            ViewBag.UserName = _services.GetNameUser(saveHoaDonDTO.IdUser);
            return View(saveHoaDonDTO);
        }

        [HttpPost]
        public IActionResult Edit(SaveHoaDonDTO SaveHoaDonDTO)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (!ModelState.IsValid)
            {
                ViewData["ListBanAn"] = _services.GetListBanAn();
                ViewBag.UserName = _services.GetNameUser(SaveHoaDonDTO.IdUser);
                return View(SaveHoaDonDTO);
            }
            _services.Edit(SaveHoaDonDTO);
            return RedirectToAction("Index");
        }
    }
}

Source/QuanLyNhaHang/Controllers/HomeQuanLyController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ApplicationCore.Interfaces.IServices;
using QuanLyNhaHang.Services.Interfaces;
using ApplicationCore.DTOs;

namespace QLNH.Controllers
{

    public class HomeQuanLyController : Controller
    {
        // GET: QuanLy/HomeQuanLy
        private readonly INguoiDungServices _services;
        private readonly INguoiDungIndexVMServices _servicesIndexVM;
        public HomeQuanLyController(INguoiDungServices services, INguoiDungIndexVMServices servicesIndexVM)
        {
            this._services = services;
            this._servicesIndexVM = servicesIndexVM;
        }
        public IActionResult Index()
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            int id = Convert.ToInt32(HttpContext.Session.GetString("IdCurrentUser").ToString());
            NguoiDungDTO nguoiDung = _services.GetNguoiDung(id);
            ViewBag.Time = DateTime.Now;
            return View(nguoiDung);
        }
        public bool KiemTraDangNhap()
        {
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("TenDangNhapCurrentUser")))
            {
                return false;
            }
            else
            {
                ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                return true;
            }
        }
    }
}

Source/QuanLyNhaHang/Controllers/KhachHangController.cs
using System;
using ApplicationCore.DTOs.SaveDTOs;
using ApplicationCore.Interfaces.IServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuanLyNhaHang.Services.Interfaces;
using QuanLyNhaHang.ViewModels;

namespace QuanLyNhaHang.Controllers
{
    public class KhachHangController : Controller
    {
        private readonly IKhachHangServices _services;
        private readonly IKhachHangIndexVMServices _servicesIndexVM;
        public KhachHangController(IKhachHangServices services, IKhachHangIndexVMServices servicesIndexVM)
        {
            this._services = services;
            this._servicesIndexVM = servicesIndexVM;
        }

        public bool KiemTraDangNhap()
        {
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("TenDangNhapCurrentUser")))
            {
                return false;
            }
            else
            {
                ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                return true;
            }
        }
        public IActionResult Index(string Ten, string SDT, string DiaChi, string currentSort, string currentFilterTen, string currentFilterSDT, string currentFilterDiaChi, int pageIndex = 1)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (!String.IsNullOrEmpty(Ten) || !String.IsNullOrEmpty(SDT) || !String.IsNullOrEmpty(DiaChi))
                pageIndex = 1;
            if (String.IsNullOrEmpty(Ten))
                Ten = currentFilterTen;
            if (String.IsNullOrEmpty(SDT))
                SDT = currentFilterSDT;
            if (String.IsNullOrEmpty(DiaChi))
                DiaChi = currentFilterDiaChi;
            @ViewBag.CurrentFilterTen = Ten;
            @ViewBag.CurrentFilterSDT = SDT;
            @ViewBag.CurrentFilterDiaChi = DiaChi;
            if (String.IsNullOrEmpty(currentSort))
                currentSort = "Ten_DESC";
            @ViewBag.CurrentSortTen = currentSort.Equals("Ten_DESC") ? "Ten_ASC" : "Ten_DESC";
            @ViewBag.CurrentSortSDT = currentSort.Equals("SDT_DESC") ? "SDT_ASC" : "SDT_DESC";
            @ViewBag.CurrentSortDiaChi = currentSort.Equals("DiaChi_DESC") ? "DiaChi_ASC" : "DiaChi_DESC";

            @ViewBag.CurrentSort = currentSort;
            KhachHangVM khachHangVM = _servicesIndexVM.GetKhachHangVM(currentSort, Ten, SDT, DiaChi, pageIndex);
            return View(khachHangVM);
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            return View();
        }

        [HttpPost]
        public IActionResult Create(SaveKhachHangDTO SaveKhachHangDTO)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (!ModelState.IsValid)
            {
                return View(SaveKhachHangDTO);
            }
            _services.Create(SaveKhachHangDTO);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            SaveKhachHangDTO saveKhachHangDTO = _services.GetSaveKhachHangDTO(id.Value);
            if (saveKhachHangDTO == null)
                return RedirectToAction("Index");
            return View(saveKhachHangDTO);
        }
        [HttpPost]
        public IActionResult Edit(SaveKhachHangDTO saveKhachHangDTO)
        {
            if (!ModelState.IsValid)
                return View(saveKhachHangDTO);
            _services.Edit(saveKhachHangDTO);
            return RedirectToAction("Index");
        }

        public IActionResult Detail(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            return View(_services.GetKhachHang(id.Value));
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            return View(_services.GetSaveKhachHangDTO(id.Value));
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult Deleted(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            int i = _services.Delete(id.Value);
            if (i.Equals(-1))
            {
                ViewBag.MessageDeleteError = "Danh sách phiếu đặt bàn của khách hàng bị null";
                return View(_services.GetSaveKhachHangDTO(id.Value));
            }
            else if (i.Equals(0))
            {
                ViewBag.MessageDeleteError = "Khách hàng này đã có phiếu đặt bàn, không thể xóa";
                return View(_services.GetSaveKhachHangDTO(id.Value));
            }
            return RedirectToAction("Index");
        }
    }
}

Source/QuanLyNhaHang/Controllers/ThongKeController.cs
using System;
using ApplicationCore.Interfaces.IServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuanLyNhaHang.Services.Interfaces;

namespace QuanLyNhaHang.Controllers
{
    public class ThongKeController : Controller
    {
        private readonly IThongKeServices _services;
        private readonly IThongKeIndexVMServices _servicesIndexVM;
        public ThongKeController(IThongKeServices services, IThongKeIndexVMServices servicesIndexVM)
        {
            this._services = services;
            this._servicesIndexVM = servicesIndexVM;
        }
        public bool KiemTraDangNhap()
        {
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("TenDangNhapCurrentUser")))
            {
                return false;
            }
            else
            {
                ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                return true;
            }
        }
        public IActionResult Index(string thoiGianTu, string thoiGianDen, string currentFilterThoiGianTu, string currentFilterThoiGianDen, string currentSort, int pageIndex = 1)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (thoiGianTu != null || thoiGianDen != null)
                pageIndex = 1;
            if (thoiGianTu == null)
                thoiGianTu = currentFilterThoiGianTu;
            if (thoiGianDen == null)
                thoiGianDen = currentFilterThoiGianDen;

            ViewBag.CurrentFilterThoiGianTu = thoiGianTu;
            ViewBag.CurrentFilterThoiGianDen = thoiGianDen;

            if (String.IsNullOrEmpty(currentSort))
                currentSort = "TenLoaiMonAn_DESC";

            ViewBag.CurrentSortTenLoaiMonAn = currentSort.Equals("TenLoaiMonAn_DESC") ? "TenLoaiMonAn_ASC" : "TenLoaiMonAn_DESC";
            ViewBag.CurrentSortTenMonAn = currentSort.Equals("TenMonAn_DESC") ? "TenMonAn_ASC" : "TenMonAn_DESC";
            ViewBag.CurrentSortGia = currentSort.Equals("Gia_DESC") ? "Gia_ASC" : "Gia_DESC";
            ViewBag.CurrentSortSLBanDuoc = currentSort.Equals("SLBanDuoc_DESC") ? "SLBanDuoc_ASC" : "SLBanDuoc_DESC";

            ViewBag.CurrentSort = currentSort;
            DateTime tgTu = new DateTime();
            if (!String.IsNullOrEmpty(thoiGianTu))
                tgTu = Convert.ToDateTime(thoiGianTu);

            DateTime tgDen = DateTime.Now;
            if (!String.IsNullOrEmpty(thoiGianDen))
                tgDen = Convert.ToDateTime(thoiGianDen);

            return View(_servicesIndexVM.GetThongKeVM(currentSort, tgTu, tgDen, pageIndex));
        }
    }
}

Source/QuanLyNhaHang/Views/HomeQuanLy/Index.cshtml
@model ApplicationCore.DTOs.NguoiDungDTO
@{
    ViewBag.Title = "Trang chủ";
}

		<div class="row">
            <div class="col-lg-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Xin chào!</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div style="margin-left:20px">
                            <p>Người dùng : @Model.Ten</p>
                            <p>Vai trò : @Model.Role</p>
                            <p>Thời gian hiện tại: @ViewBag.Time</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="x_panel">
                    <div class="x_content">
                        <div class="bs-glyphicons">
                            <ul class="bs-glyphicons-list">
                                <a asp-action="Index" asp-controller="HomeQuanLy">
                                    <li>   
                                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                                        <span class="glyphicon-class">Trang chủ</span>
                                    </li>
                                 </a>
                                <a asp-action="Index" asp-controller="ThucDon">
                                    <li>
                                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
                                        <span class="glyphicon-class">Quản lý thực đơn</span>
                                    </li>
                                </a>
                                <a asp-action="Index" asp-controller="BanAn">
                                     <li>
                                        <span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>
                                        <span class="glyphicon-class">Quản lý bàn ăn</span>
                                    </li>
                                </a>
                                <a asp-action="Index" asp-controller="LoaiMonAn">
                                    <li>
                                        <span class="glyphicon glyphicon-indent-right" aria-hidden="true"></span>
                                        <span class="glyphicon-class">Quản lý loại món ăn</span>
                                    </li>
                                </a>

                                <a asp-action="Index" asp-controller="HoaDon">
                                    <li>
                                        <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
                                        <span class="glyphicon-class">Quản lý hóa đơn</span>
                                    </li>
                                </a>
                                <a asp-action="Index" asp-controller="NguoiDung">
                                    <li>
                                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                        <span class="glyphicon-class">Quản lý người dùng</span>
                                    </li>
                                </a>
                                <a asp-action="Index" asp-controller="KhachHang">
                                    <li>
                                        <span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span>
                                        <span class="glyphicon-class">Quản lý khách hàng</span>
                                    </li>
                                </a>
                                <a asp-action="Index" asp-controller="ThongKe">
                                     <li>
                                        <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
                                        <span class="glyphicon-class">Thống kê</span>
                                    </li>
                                </a>
                                
                            </ul>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>