Source/QuanLyNhaHang/Controllers/HoaDonController.cs
using System;
using System.Reflection.Metadata;
using ApplicationCore.DTOs;
using ApplicationCore.DTOs.SaveDTOs;
using ApplicationCore.Interfaces.IServices;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuanLyNhaHang.Services.Interfaces;

namespace QuanLyNhaHang.Controllers
{
    public class HoaDonController : Controller
    {
        private readonly IHoaDonServices _services;
        private readonly IHoaDonIndexVMServices _servicesIndexVM;
        private readonly IMapper _mapper;
        public HoaDonController(IHoaDonServices services, IHoaDonIndexVMServices servicesIndexVM, IMapper mapper)
        {
            this._services = services;
            this._servicesIndexVM = servicesIndexVM;
            this._mapper = mapper;
        }
        public bool KiemTraDangNhap()
        {
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("TenDangNhapCurrentUser")))
            {
                return false;
            }
            else
            {
                ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                return true;
            }
        }
        public IActionResult Index(int idBanAn, string trangThai, string currentSort, string currentFilterIdBanAn, string currentFilterTrangThai, int pageIndex = 1)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (String.IsNullOrEmpty(idBanAn.ToString()))
                idBanAn = 0;
            if (!idBanAn.Equals(0))
            {
                pageIndex = 1;
            }
            else if (!String.IsNullOrEmpty(currentFilterIdBanAn))
            {
                idBanAn = Convert.ToInt32(currentFilterIdBanAn.ToString());
            }
            
            if (!String.IsNullOrEmpty(trangThai))
            {
                pageIndex = 1;
            }
            else
            {
                trangThai = currentFilterTrangThai;
            }
            ViewBag.CurrentFilterTrangThai = trangThai;
            ViewBag.CurrentFilterIdBanAn = idBanAn;
           
            if (String.IsNullOrEmpty(currentSort))
                currentSort = "BanAn_DESC";

            ViewBag.CurrentSortIdBanAn = currentSort.Equals("BanAn_DESC") ? "BanAn_ASC" : "BanAn_DESC";
            ViewBag.CurrentSortTrangThai = currentSort.Equals("TrangThai_DESC") ? "TrangThai_ASC" : "TrangThai_DESC";
            ViewBag.CurrentSortThoiGianLap = currentSort.Equals("ThoiGianLap_DESC") ? "ThoiGianLap_ASC" : "ThoiGianLap_DESC";
            ViewBag.CurrentSortThoiGianThanhToan = currentSort.Equals("ThoiGianThanhToan_DESC") ? "ThoiGianThanhToan_ASC" : "ThoiGianThanhToan_DESC";
            ViewBag.CurrentSortTenNhanVien = currentSort.Equals("TenNhanVien_DESC") ? "TenNhanVien_ASC" : "TenNhanVien_DESC";
            ViewBag.CurrentSortThanhTien = currentSort.Equals("ThanhTien_DESC") ? "ThanhTien_ASC" : "ThanhTien_DESC";
            ViewBag.CurrentSortIdHoaDon = currentSort.Equals("IdHoaDon_DESC") ? "IdHoaDon_ASC" : "IdHoaDon_DESC";

            ViewBag.CurrentSort = currentSort;
            return View(_servicesIndexVM.GetHoaDonVM(currentSort, idBanAn, trangThai, pageIndex));
        }
        public IActionResult Delete(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (id == null)
                return RedirectToAction("Index");
            HoaDonDTO hoaDonDTO = _services.FindHD(id.Value);
            if (hoaDonDTO == null)
                return RedirectToAction("Index");
            ViewBag.UserName = _services.GetNameUser(hoaDonDTO.IdUser);
            SaveHoaDonDTO saveHoaDonDTO = _mapper.Map<HoaDonDTO, SaveHoaDonDTO>(hoaDonDTO);
            return View(saveHoaDonDTO);
        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult Deleted(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (id == null)
                return RedirectToAction("Index");

            int i = _services.Delete(id.Value);
            if (i == 0)
            {
                ViewBag.Error = "Hóa đơn này đang tính cho bàn ăn đang được phục vụ ,không thể xóa ";
                HoaDonDTO hoaDonDTO = _services.FindHD(id.Value);
                SaveHoaDonDTO saveHoaDonDTO = _mapper.Map<HoaDonDTO, SaveHoaDonDTO>(hoaDonDTO);
                ViewBag.UserName = _services.GetNameUser(hoaDonDTO.IdUser);
                return View(saveHoaDonDTO);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Details(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (id == null)
                return RedirectToAction("Index");
            HoaDonDTO hoaDonDTO = _services.FindHD(id.Value);
            if (hoaDonDTO == null)
                return RedirectToAction("Index");
            ViewBag.UserName = _services.GetNameUser(hoaDonDTO.IdUser);
            return View(_servicesIndexVM.Details(id.Value));
        }
        public IActionResult Edit(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (id == null)
                return RedirectToAction("Index");
            ViewData["ListBanAn"] = _services.GetListBanAn();
            SaveHoaDonDTO saveHoaDonDTO = _mapper.Map<HoaDonDTO, SaveHoaDonDTO>(_services.FindHD(id.Value));
            ViewBag.UserName = _services.GetNameUser(saveHoaDonDTO.IdUser);
            return View(saveHoaDonDTO);
        }

        [HttpPost]
        public IActionResult Edit(SaveHoaDonDTO SaveHoaDonDTO)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (!ModelState.IsValid)
            {
                ViewData["ListBanAn"] = _services.GetListBanAn();
                ViewBag.UserName = _services.GetNameUser(SaveHoaDonDTO.IdUser);
                return View(SaveHoaDonDTO);
            }
            _services.Edit(SaveHoaDonDTO);
            return RedirectToAction("Index");
        }
    }
}

Source/QuanLyNhaHang/Controllers/LoaiMonAnController.cs
using System;
using System.Globalization;
using ApplicationCore.DTOs;
using ApplicationCore.DTOs.SaveDTOs;
using ApplicationCore.Interfaces.IServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuanLyNhaHang.Services.Interfaces;
using QuanLyNhaHang.ViewModels;

namespace QuanLyNhaHang.Controllers
{
    public class LoaiMonAnController : Controller
    {
        private readonly ILoaiMonAnServices _services;
        private readonly ILoaiMonAnIndexVMServices _servicesIndexVm;
        public LoaiMonAnController(ILoaiMonAnServices services, ILoaiMonAnIndexVMServices servicesIndexVM)
        {
            this._services = services;
            this._servicesIndexVm = servicesIndexVM;
        }

        public bool KiemTraDangNhap()
        {
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("TenDangNhapCurrentUser")))
            {
                return false;
            }
            else
            {
                ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                return true;
            }
        }

        public IActionResult Index(string currentSort, string currentFilter, string searchString, int pageIndex = 1)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (!String.IsNullOrEmpty(searchString))
            {
                pageIndex = 1;
            }
            else
                searchString = currentFilter;

            if (String.IsNullOrEmpty(currentSort))
                currentSort = "TEN_DESC";


            ViewBag.CurrentSortName = currentSort.Equals("TEN_DESC") ? "TEN_ASC" : "TEN_DESC";
            ViewBag.CurrentSort = currentSort;
            ViewBag.CurrentFilter = searchString;
            LoaiMonAnVM loaiMonAnVM = _servicesIndexVm.GetLoaiMonAnVM(currentSort, searchString, pageIndex);

            return View(loaiMonAnVM);
        }

        [HttpPost]
        public IActionResult Create(string TenLoaiMonAn)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (String.IsNullOrEmpty(TenLoaiMonAn))
                return RedirectToAction("Index");
            SaveLoaiMonAnDTO save = new SaveLoaiMonAnDTO { Ten = TenLoaiMonAn };
            _services.Create(save);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (id == null)
                return RedirectToAction("Index");
            SaveLoaiMonAnDTO loaiMonAnDTO = _services.GetSaveLoaiMonAnDTO(id.Value);
            return View(loaiMonAnDTO);
        }
        [HttpPost]
        public IActionResult Edit(SaveLoaiMonAnDTO saveLoaiMonAnDTO)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (!ModelState.IsValid)
                return View(saveLoaiMonAnDTO);
            _services.Edit(saveLoaiMonAnDTO);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (id == null)
                return RedirectToAction("Index");
            LoaiMonAnDTO loaiMonAnDTO = _services.GetLoaiMonAn(id.Value);
            return View(loaiMonAnDTO);
        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult Deleted(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (id == null)
                return RedirectToAction("Index");
            int i = _services.Delete(id.Value);
            if (i == -1)
            {
                ViewBag.MessageError = "Loại món ăn này đã có món ăn, không thể xóa";
                LoaiMonAnDTO loaiMonAnDTO = _services.GetLoaiMonAn(id.Value);
                return View(loaiMonAnDTO);
            }
            return RedirectToAction("Index");
        }
    }


}

Source/QuanLyNhaHang/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using ApplicationCore.DTOs;
using ApplicationCore.Entities;
using ApplicationCore.Interfaces.IServices;
using ApplicationCore.ModelsContainData.Models;
using Infrastructure.Persistence.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace QuanLyNhaHang.Controllers
{
    public class LoginController : Controller
    {
        private readonly INguoiDungServices _services;
        public LoginController(INguoiDungServices services)
        {
            this._services = services;

        }
        public IActionResult Index()
        {
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("TenDangNhapCurrentUser")) == false)
            {
                ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                return View("../HomeQuanLy/Index");
            }
            return View();
        }

        public string GetMd5Hash(MD5 md5, string input)
        {
            byte[] bytes = md5.ComputeHash(Encoding.UTF8.GetBytes(input));
            StringBuilder s = new StringBuilder();
            for (int i = 0; i < bytes.Length; i++)
            {
                s.Append(bytes[i].ToString("X2"));

            }
            return s.ToString();

        }

        public bool VerifyMd5Hash(MD5 md5, string input, string sqlString)
        {
            string md5Hash = GetMd5Hash(md5, input);
            if (md5Hash.Equals(sqlString))
                return true;
            return false;
        }

        [HttpPost]
        public IActionResult Index(Account user)
        {

            string userName = user.Username;
            NguoiDungDTO nd = _services.GetNguoiDungDTOByUserName(userName);
            if (nd == null)
            {
                ViewBag.Message = "Không có người dùng này";
                return View("Index");
            }
            using (MD5 md5 = MD5.Create())
            {
                if (VerifyMd5Hash(md5, user.Password, nd.MatKhau))
                {
                    if (nd.TrangThai.Equals(-1))
                    {
                        ViewBag.Message = "Tài khoản này đã bị khóa";
                        return View("Index");
                    }
                    HttpContext.Session.SetString("TenDangNhapCurrentUser", nd.TenDangNhap);
                    HttpContext.Session.SetString("IdCurrentUser", nd.Id.ToString());
                    HttpContext.Session.SetString("TenCurrentUser", nd.Ten);
                    HttpContext.Session.SetString("TrangThaiCurrentUser", nd.TrangThai.ToString());
                    HttpContext.Session.SetString("VaiTroCurrentUser", nd.Role);
                    HttpContext.Session.SetString("MatKhauCurrentUser", nd.MatKhau);

                    ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                    ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                    ViewBag.Time = DateTime.Now;
                    return View("../HomeQuanLy/Index",nd);
                }
                else
                {
                    ViewBag.Message = "Sai mật khẩu";
                    return View();
                }
            }

        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("TenDangNhapCurrentUser");
            HttpContext.Session.Clear();
            return View("../Login/Index");
        }
    }
}

Source/QuanLyNhaHang/Controllers/ThongKeController.cs
using System;
using ApplicationCore.Interfaces.IServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuanLyNhaHang.Services.Interfaces;

namespace QuanLyNhaHang.Controllers
{
    public class ThongKeController : Controller
    {
        private readonly IThongKeServices _services;
        private readonly IThongKeIndexVMServices _servicesIndexVM;
        public ThongKeController(IThongKeServices services, IThongKeIndexVMServices servicesIndexVM)
        {
            this._services = services;
            this._servicesIndexVM = servicesIndexVM;
        }
        public bool KiemTraDangNhap()
        {
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("TenDangNhapCurrentUser")))
            {
                return false;
            }
            else
            {
                ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                return true;
            }
        }
        public IActionResult Index(string thoiGianTu, string thoiGianDen, string currentFilterThoiGianTu, string currentFilterThoiGianDen, string currentSort, int pageIndex = 1)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (thoiGianTu != null || thoiGianDen != null)
                pageIndex = 1;
            if (thoiGianTu == null)
                thoiGianTu = currentFilterThoiGianTu;
            if (thoiGianDen == null)
                thoiGianDen = currentFilterThoiGianDen;

            ViewBag.CurrentFilterThoiGianTu = thoiGianTu;
            ViewBag.CurrentFilterThoiGianDen = thoiGianDen;

            if (String.IsNullOrEmpty(currentSort))
                currentSort = "TenLoaiMonAn_DESC";

            ViewBag.CurrentSortTenLoaiMonAn = currentSort.Equals("TenLoaiMonAn_DESC") ? "TenLoaiMonAn_ASC" : "TenLoaiMonAn_DESC";
            ViewBag.CurrentSortTenMonAn = currentSort.Equals("TenMonAn_DESC") ? "TenMonAn_ASC" : "TenMonAn_DESC";
            ViewBag.CurrentSortGia = currentSort.Equals("Gia_DESC") ? "Gia_ASC" : "Gia_DESC";
            ViewBag.CurrentSortSLBanDuoc = currentSort.Equals("SLBanDuoc_DESC") ? "SLBanDuoc_ASC" : "SLBanDuoc_DESC";

            ViewBag.CurrentSort = currentSort;
            DateTime tgTu = new DateTime();
            if (!String.IsNullOrEmpty(thoiGianTu))
                tgTu = Convert.ToDateTime(thoiGianTu);

            DateTime tgDen = DateTime.Now;
            if (!String.IsNullOrEmpty(thoiGianDen))
                tgDen = Convert.ToDateTime(thoiGianDen);

            return View(_servicesIndexVM.GetThongKeVM(currentSort, tgTu, tgDen, pageIndex));
        }
    }
}

Source/QuanLyNhaHang/Views/Shared/_LeftMenu.cshtml
@{
    Layout = null;
}

    <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a asp-action="Index" asp-controller="HomeQuanLy" class="site_title"><i class="fa fa-home"></i> <span>Quản lý nhà hàng</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                            <li>
                                <a asp-controller="HomeQuanLy" asp-action="Index"><i class="fa fa-globe fa-fw"></i> Home</a>
                            </li>
                            <li>
                                <a asp-controller="ThucDon" asp-action="Index"><i class="fa fa-coffee fa-fw"></i> Quản lý thực đơn </a>
                            </li>
                             <li>
                                <a asp-controller="BanAn" asp-action="Index"><i class="fa fa-cutlery fa-fw"></i> Quản lý bàn ăn </a>
                            </li>
                            <li>
                                <a asp-controller="LoaiMonAn" asp-action="Index"><i class="fa fa-briefcase fa-fw"></i> Quản lý loại thức ăn </a>
                            </li>
                            <li>
                                <a asp-controller="HoaDon" asp-action="Index"><i class="fa fa-list-alt fa-fw"></i> Quản lý hóa đơn </a>
                            </li>
                           
                            <li>
                                <a asp-controller="PhieuDatBan" asp-action="Index"><i class="fa fa-bookmark fa-fw"></i> Quản lý phiếu đặt bàn </a>
                            </li>
                            <li>
                                <a asp-controller="KhachHang" asp-action="Index"><i class="fa fa-users fa-fw"></i> Quản lý khách hàng</a>
                            </li>
                            <li>
                                <a asp-controller="NguoiDung" asp-action="Index"><i class="fa fa-user fa-fw"></i> Quản lý người dùng</a>
                            </li>
                            <li>
                                <a asp-controller="ThongKe" asp-action="Index"><i class="fa fa-bar-chart fa-fw"></i> Thống kê</a>
                            </li>
                  
                </ul>
              </div>
              

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" asp-controller="Login" asp-action="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
        </div>
    </div>


            

Source/QuanLyNhaHang/Views/Shared/_LeftMenuNhanVien.cshtml
@{
    Layout = null;
}

    <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a asp-action="Index" asp-controller="HomeQuanLy" class="site_title"><i class="fa fa-home"></i> <span>Quản lý nhà hàng</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                            <li>
                                <a asp-controller="HomeQuanLy" asp-action="Index"><i class="fa fa-globe fa-fw"></i> Home</a>
                            </li>
                            <li>
                                <a asp-controller="ThucDon" asp-action="Index"><i class="fa fa-coffee fa-fw"></i> Quản lý thực đơn </a>
                            </li>
                             <li>
                                <a asp-controller="BanAn" asp-action="Index"><i class="fa fa-cutlery fa-fw"></i> Quản lý bàn ăn </a>
                            </li>
                            <li>
                                <a asp-controller="LoaiMonAn" asp-action="Index"><i class="fa fa-briefcase fa-fw"></i> Quản lý loại thức ăn </a>
                            </li>
                            <li>
                                <a asp-controller="HoaDon" asp-action="Index"><i class="fa fa-list-alt fa-fw"></i> Quản lý hóa đơn </a>
                            </li>
                           
                            <li>
                                <a asp-controller="PhieuDatBan" asp-action="Index"><i class="fa fa-bookmark fa-fw"></i> Quản lý phiếu đặt bàn </a>
                            </li>
                            <li>
                                <a asp-controller="KhachHang" asp-action="Index"><i class="fa fa-users fa-fw"></i> Quản lý Khách hàng</a>
                            </li>
                            <li>
                                <a asp-controller="ThongKe" asp-action="Index"><i class="fa fa-bar-chart fa-fw"></i> Thống kê</a>
                            </li>
                  
                </ul>
              </div>
              

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" asp-controller="Login" asp-action="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
        </div>
    </div>


            

Source/QuanLyNhaHang/Views/Shared/_TopMenu.cshtml
@{
    Layout = null;
}
        <div class="top_nav">
          <div class="nav_menu">
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
              <nav class="nav navbar-nav">
              <ul class=" navbar-right">
                <li class="nav-item dropdown open" style="padding-left: 15px;">
                  <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                    <img src="" alt="">@ViewBag.TenCurrentUser
                  </a>
                  <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item"  asp-action="Profile" asp-controller="NguoiDung"> Profile</a>
                    <a  class="dropdown-item" asp-controller="Login" asp-action="Logout"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                  </div>
                </li>
              </ul>
            </nav>
          </div>
        </div>