Source/QuanLyNhaHang/Controllers/NguoiDungController.cs
using System;
using ApplicationCore.Interfaces.IServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuanLyNhaHang.Services.Interfaces;
using ApplicationCore.DTOs.SaveDTOs;
using ApplicationCore.DTOs;
using QuanLyNhaHang.ViewModels;

namespace QuanLyNhaHang.Controllers
{
    public class NguoiDungController : Controller
    {
        private readonly INguoiDungServices _services;
        private readonly INguoiDungIndexVMServices _servicesIndexVM;
        public NguoiDungController(INguoiDungServices services, INguoiDungIndexVMServices servicesIndexVM)
        {
            this._services = services;
            this._servicesIndexVM = servicesIndexVM;
        }

        public bool KiemTraDangNhap()
        {
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("TenDangNhapCurrentUser")))
            {
                return false;
            }
            else
            {
                ViewBag.TenCurrentUser = HttpContext.Session.GetString("TenCurrentUser").ToString();
                ViewBag.IdCurrentUser = HttpContext.Session.GetString("IdCurrentUser").ToString();
                return true;
            }
        }

        public IActionResult Index(string Ten, string TenDangNhap, string VaiTro, int TrangThai, string currentSort, string currentFilterTen, string currentFilterTenDangNhap, string currentFilterVaiTro, string currentFilterTrangThai, int pageIndex = 1)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (!String.IsNullOrEmpty(Ten) || !String.IsNullOrEmpty(TenDangNhap) || !String.IsNullOrEmpty(VaiTro) || !TrangThai.Equals(0))
                pageIndex = 1;
            if (String.IsNullOrEmpty(Ten))
                Ten = currentFilterTen;
            if (String.IsNullOrEmpty(TenDangNhap))
                TenDangNhap = currentFilterTenDangNhap;
            if (String.IsNullOrEmpty(VaiTro))
                VaiTro = currentFilterVaiTro;
            if (TrangThai.Equals(0) && !String.IsNullOrEmpty(currentFilterTrangThai))
                TrangThai = Convert.ToInt32(currentFilterTrangThai);
            ViewBag.CurrentFilterTen = Ten;
            ViewBag.CurrentFilterTenDangNhap = TenDangNhap;
            ViewBag.CurrentFilterVaiTro = VaiTro;
            ViewBag.CurrentFilterTrangThai = TrangThai;
            if (String.IsNullOrEmpty(currentSort))
                currentSort = "Ten_DESC";

            ViewBag.CurrentSortTen = currentSort.Equals("Ten_DESC") ? "Ten_ASC" : "Ten_DESC";
            ViewBag.CurrentSortTenDangNhap = currentSort.Equals("TenDangNhap_DESC") ? "TenDangNhap_ASC" : "TenDangNhap_DESC";
            ViewBag.CurrentSortVaiTro = currentSort.Equals("VaiTro_DESC") ? "VaiTro_ASC" : "VaiTro_DESC";
            ViewBag.CurrentSortTrangThai = currentSort.Equals("TrangThai_DESC") ? "TrangThai_ASC" : "TrangThai_DESC";

            ViewBag.CurrentSort = currentSort;
            NguoiDungVM nguoiDungVM = _servicesIndexVM.GetNguoiDungVM(currentSort, Ten, TenDangNhap, VaiTro, TrangThai, pageIndex);
            return View(nguoiDungVM);
        }
        [HttpGet]
        public IActionResult Create()
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            return View();
        }

        [HttpPost]
        public IActionResult Create(string NhapLaiMatKhau, SaveNguoiDungDTO SaveNguoiDungDTO)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");
            if (!ModelState.IsValid)
            {
                return View(NhapLaiMatKhau, SaveNguoiDungDTO);
            }
            int i = _services.Create(NhapLaiMatKhau, SaveNguoiDungDTO);
            if (i == -1)
            {
                ViewBag.MessageErrorNhapLaiMatKhau = "Mật khẩu nhập lại không khớp";
                return View(SaveNguoiDungDTO);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (id == null)
                return RedirectToAction("Index");
            SaveNguoiDungDTO saveNguoiDungDTO = _services.GetSaveNguoiDungDTO(id.Value);
            if (saveNguoiDungDTO == null)
                return RedirectToAction("Index");
            return View(saveNguoiDungDTO);
        }
        [HttpPost]
        public IActionResult Edit(SaveNguoiDungDTO saveNguoiDungDTO)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (!ModelState.IsValid)
                return View(saveNguoiDungDTO);
            _services.Edit(saveNguoiDungDTO);
            return RedirectToAction("Index");
        }

        public IActionResult LockUser(int? id)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            if (id == null)
                return RedirectToAction("Index");
            int idCurrentUser = Convert.ToInt32(HttpContext.Session.GetString("IdCurrentUser"));
            int i = _services.LockUser(id.Value, idCurrentUser);
            if (i == -1)
            {
                ViewData["MessageLockUser"] = "Không thể khóa vì bạn là người dùng này và đang sử dụng tài khoản này";
            }
            return RedirectToAction("Index");
        }

        public IActionResult Profile()
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            int IdUser = Convert.ToInt32(HttpContext.Session.GetString("IdCurrentUser"));
            if (IdUser == 0)
                return View("../Login/Index");
            NguoiDungDTO nguoiDungDTO = _services.GetNguoiDung(IdUser);
            if (nguoiDungDTO == null)
                return View("../Login/Index");
            return View(_servicesIndexVM.GetUserProfileVM(IdUser));
        }

        [HttpPost]
        public IActionResult SuaThongTinCaNhan(int IdUser, string HoTen)
        {
            if (KiemTraDangNhap() == false)
                return View("../Login/Index");

            _services.SuaThongTinCaNhan(IdUser, HoTen);
            HttpContext.Session.SetString("TenCurrentUser", HoTen);
            return RedirectToAction("Profile");
        }

        [HttpPost]
        public string DoiMatKhau(string IdUser, string MatKhauMoi, string MatKhauCu)
        {
            int id = 0;
            if (String.IsNullOrEmpty(IdUser) == false)
                id = Convert.ToInt32(IdUser);
            string i = _services.DoiMatKhau(id, MatKhauMoi, MatKhauCu);
            if (i.Equals("0"))
            {
                return "0";
            }
            if (i.Equals("1"))
            {
                HttpContext.Session.SetString("MatKhauCurrentUser", MatKhauMoi);
                return "1";
            }
            else
                return "-1";
        }
    }
}

Source/QuanLyNhaHang/Views/NguoiDung/Create.cshtml
@model ApplicationCore.DTOs.SaveDTOs.SaveNguoiDungDTO

@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenDangNhap" class="control-label"></label>
                <input asp-for="TenDangNhap" class="form-control" />
                <span asp-validation-for="TenDangNhap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatKhau" class="control-label"></label>
                <input asp-for="MatKhau" class="form-control" type="password"/>
                <span asp-validation-for="MatKhau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Nhập lại mật khẩu</label>
                <input name="NhapLaiMatKhau" class="form-control" type="password"/>
                <i style="color:red">@ViewBag.MessageErrorNhapLaiMatKhau</i>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <select asp-for="Role" style="padding:5px;margin-left:20px">
                    <option value="Nhân viên">Nhân viên</option>
                    <option value="Quản lý" >Quản lý</option>                       
                </select>
            </div>
            <div class="form-group">
                <input asp-for="TrangThai" class="form-control" value="1" type="hidden"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Source/QuanLyNhaHang/Views/NguoiDung/Profile.cshtml
@model QuanLyNhaHang.ViewModels.UserProfileVM

@{
    ViewData["Title"] = "Quản lý hồ sơ cá nhân";
}

<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_title">
                <h2>Hồ sơ cá nhân</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-3 col-sm-3  profile_left">
                    <div class="profile_img">
                        <div id="crop-avatar">
                          <!-- Current avatar -->
                          <img class="img-responsive avatar-view" style="width:100%;height:100%"src="~/Images/picture.png" alt="Avatar" title="Avatar">
                        </div>
                    </div>
                </div>

                <div class="col-md-9 col-sm-9 ">
                    <div class="profile_title">
                        <div class="col-md-12">
                          <h2>Thông tin người dùng</h2>
                        </div>
                    </div>

                    <div class="col-md-11" style="margin-left:10px">
                            <dl class="row">
                                <dt class = "col-sm-2">
                                    @Html.DisplayNameFor(model => model.NguoiDungDTO.Ten)
                                </dt>
                                <dd class = "col-sm-10">
                                    @Html.DisplayFor(model => model.NguoiDungDTO.Ten)
                                </dd>
                                <dt class = "col-sm-2">
                                    @Html.DisplayNameFor(model => model.NguoiDungDTO.TenDangNhap)
                                </dt>
                                <dd class = "col-sm-10">
                                    @Html.DisplayFor(model => model.NguoiDungDTO.TenDangNhap)
                                </dd>
                                <dt class = "col-sm-2">
                                    @Html.DisplayNameFor(model => model.NguoiDungDTO.Role)
                                </dt>
                                <dd class = "col-sm-10">
                                    @Html.DisplayFor(model => model.NguoiDungDTO.Role)
                                </dd>
                            </dl>
                            <div>
                                <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#SuaThongTinCaNhanModal">Sửa thông tin cá nhân</button>
                                <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#DoiMatKhauModal">Đổi mật khẩu</button>
                                <div>
                                   
                                </div>
                            </div>
                    </div>
                    
                    <div class="clearfix"></div>
                </div>

                <div class="col-md-12">
                    <div class="col-md-12" style="margin-top:10px">
                        <div class="profile_title">
                            <div class="col-md-12">
                                <h2>Hoạt động gần đây  <small>  Danh sách bàn ăn đã phục vụ</small></h2>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <table class="table table-striped jambo_table no-margin">
                                <thead>
                                    <tr>
                                        <th>Bàn ăn</th>
                                        <th>Thời gian lập</th>
                                        <th>Thời gian thanh toán</th>
                                        <th>Thành tiền</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ( var item in Model.ListHD )
                                    {
                                        <tr>
                                            <td> @item.IdBanAn</td> 
                                            <td> @item.ThoiGianLap</td> 
                                            <td> @item.ThoiGianThanhToan</td> 
                                            <td> @item.ThanhTien</td> 
                                        </tr>
                                    }
                                        
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<!-- The Modal -->
  <div class="modal fade" id="SuaThongTinCaNhanModal">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Sửa thông tin cá nhân</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
            <form asp-action="SuaThongTinCaNhan" asp-controller="NguoiDung" method="post" onsubmit="SuaTen()">
                <div class="form-group">
                    <input type="hidden" value="@ViewBag.IdCurrentUser" name="IdUser">
                    <label for="HoTen">Họ tên</label>
                    <input type="text" class="form-control" placeholder="Nhập họ tên" name="HoTen" id="HoTenUser">
                </div>
                
                <button type="submit" class="btn btn-primary" style="float:right">Submit</button>
            </form>
        </div>        
      </div>
    </div>
  </div>

  <!-- The Modal -->
  <div class="modal fade" id="DoiMatKhauModal">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Đổi mật khẩu</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
           
                <input type="hidden" value="@ViewBag.IdCurrentUser" name="IdUser" id="idu">
                <div class="form-group">
                    <label for="MatKhauCu">Mật khẩu cũ</label>
                    <input type="password" class="form-control" placeholder="Nhập mật khẩu cũ" name="MatKhauCu" id="MKCu">
                </div>
                <div class="form-group">
                    <label for="MatKhauMoi">Mật khẩu mới</label>
                    <input type="password" class="form-control" placeholder="Nhập mật khẩu mới" name="MatKhauMoi" id="MKMoi">
                </div>
                <div class="form-group">
                    <label for="NhapLaiMatKhauMoi">Nhập lại mật khẩu</label>
                    <input type="password" class="form-control" placeholder="Nhập lại mật khẩu mới" name="NhapLaiMatKhauMoi" id="NLMKMoi">
                </div>
                <div class="form-group">
                    <i id="Message" style="color:red"></i>
                </div>
                
                <button onclick="DoiMatKhau()" class="btn btn-primary" style="float:right">Submit</button>
            
        </div>
    
      </div>
    </div>
  </div>

<script>
    function SuaTen()
    {
        alert("Đổi tên thành công");
    }

    function DoiMatKhau()
    {
        var MKCu=document.getElementById("MKCu").value;
        var MKMoi=document.getElementById("MKMoi").value;
        var NLMKMoi=document.getElementById("NLMKMoi").value;
        var IdUser=document.getElementById("idu").value;
        if(MKCu=="")
        {
            document.getElementById("Message").innerHTML="Mật khẩu cũ bị trống";
            return;
        }
        else if(MKMoi=="")
        {
             document.getElementById("Message").innerHTML="Mật khẩu mới trống";
            return;
        }
        else if(NLMKMoi=="")
        {
             document.getElementById("Message").innerHTML="Mật khẩu nhập lại bị trống";
            return;
        }
        
        else if(MKMoi!=NLMKMoi)
        {
            document.getElementById("Message").innerHTML="Mật khẩu nhập lại không đúng";
            return;
        }
         var xhttp = new XMLHttpRequest();

        xhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                if(this.responseText=="0")
                    document.getElementById("Message").innerHTML = "Mật khẩu cũ không đúng";
                if(this.responseText=="1")
                    {
                        alert("Đổi mật khẩu thành công");
                        location.reload();
                    }
                if(this.responseText=="-1")
                    document.getElementById("Message").innerHTML ="Không tìm thấy người dùng này";
            }
        };
        xhttp.open("POST", "/NguoiDung/DoiMatKhau?IdUser=" + IdUser + "&MatKhauMoi="+MKMoi+"&MatKhauCu="+MKCu);
        xhttp.send();
      
    }
   
</script>